// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team4FinalProject.Data;

#nullable disable

namespace Team4FinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team4FinalProject.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Teyon",
                            Genre = "First Person Shooter",
                            Price = 1.0,
                            Title = "RoboCop: Rogue City"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "System Era Softworks",
                            Genre = "Open World Survival Craft",
                            Price = 29.989999999999998,
                            Title = "Astroneer"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "AdHoc Studio",
                            Genre = "Point & Click",
                            Price = 29.989999999999998,
                            Title = "Dispatch"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "CD PROJEKT RED",
                            Genre = "Open World RPG",
                            Price = 59.990000000000002,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Relic Entertainment",
                            Genre = "WAAAAGH Real Time Strategy",
                            Price = 29.989999999999998,
                            Title = "Warhammer 40,000: Dawn of War - Definitive Edition"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "Youthcat Studio",
                            Genre = "Base Building",
                            Price = 15.99,
                            Title = "Dyson Sphere Program"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "Blizzard Entertainment, Inc.",
                            Genre = "Action RPG",
                            Price = 39.990000000000002,
                            Title = "Diablo II: Resurrected - Infernal Edition"
                        });
                });

            modelBuilder.Entity("Team4FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExpensive")
                        .HasColumnType("bit");

                    b.Property<int>("YearsPracticed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HobbyName = "3D Printing",
                            HobbyType = "Digital",
                            IsExpensive = true,
                            YearsPracticed = 1
                        },
                        new
                        {
                            Id = 2,
                            HobbyName = "Video Games",
                            HobbyType = "Digital",
                            IsExpensive = true,
                            YearsPracticed = 30
                        },
                        new
                        {
                            Id = 3,
                            HobbyName = "Reading",
                            HobbyType = "Intellectual",
                            IsExpensive = false,
                            YearsPracticed = 35
                        },
                        new
                        {
                            Id = 4,
                            HobbyName = "Concerts",
                            HobbyType = "Physical",
                            IsExpensive = true,
                            YearsPracticed = 20
                        },
                        new
                        {
                            Id = 5,
                            HobbyName = "Traveling",
                            HobbyType = "Physical",
                            IsExpensive = true,
                            YearsPracticed = 5
                        },
                        new
                        {
                            Id = 6,
                            HobbyName = "Hiking",
                            HobbyType = "Physical",
                            IsExpensive = false,
                            YearsPracticed = 1
                        },
                        new
                        {
                            Id = 7,
                            HobbyName = "Volunteering",
                            HobbyType = "Social",
                            IsExpensive = false,
                            YearsPracticed = 0
                        });
                });

            modelBuilder.Entity("Team4FinalProject.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompiled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStronglyTyped")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                    
                    
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#",
                            Type = "Object-Oriented",
                            IsStronglyTyped = true,
                            IsCompiled = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java",
                            Type = "Object-Oriented",
                            IsStronglyTyped = true,
                            IsCompiled = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python",
                            Type = "Interpreted",
                            IsStronglyTyped = false,
                            IsCompiled = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript",
                            Type = "Scripting",
                            IsStronglyTyped = false,
                            IsCompiled = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "C++",
                            Type = "Object-Oriented",
                            IsStronglyTyped = true,
                            IsCompiled = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Go",
                            Type = "Procedural",
                            IsStronglyTyped = true,
                            IsCompiled = true
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ruby",
                            Type = "Scripting",
                            IsStronglyTyped = false,
                            IsCompiled = false
                        });
                

                });

            modelBuilder.Entity("Team4FinalProject.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "BSIT",
                            FullName = "Grant Willis",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1985, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "MSIT",
                            FullName = "Robert Mays",
                            YearInProgram = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2005, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "BSIT",
                            FullName = "William Boulle",
                            YearInProgram = "Second"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
